#!/bin/bash

#Couleur rouge
RED='\033[0;31m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'

#Pas de couleurs
NC='\033[0m'
 "${PURPLE}arrêt du serveur !${NC}"

#Relancer le serveur
echo -e "${PURPLE} Démarrage du serveur... ${NC}"
cd /home/starbound/linux && screen ./starbound_server
