#!/bin/bash

#Login MySQL
USERNAME=$(cat /root/username)
PASSWORD=$(cat /root/password)

#Couleur rouge
RED='\033[0;31m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'

#Pas de couleurs
NC='\033[0m'

#Configuration
backup_path="/home/minecraft/backups"
date=$(date +"%y-%m-%d")

# Afficher un texte, en couleur et retirer la couleur
echo -e "${PURPLE}Sauvegarde du serveur !${NC}"

#Compresser le serveur
echo -e "${BLUE} Compression des plugins en cours... ${NC}"
tar -czvf $backup_path/backup_server-"$date.tar.gz" /home/minecraft/fritecraft/ --exclude 'tiles/*'  --exclude '_worlds-archives/*'
echo -e "${PURPLE} Serveur sauvegardé !${NC}"

#Compresser les mondes
#echo -e "${BLUE} Compression des mondes en cours... ${NC}"
#tar -czf $backup_path/backup_worlds-"$date.tar.gz" /home/minecraft/fritecraft/ --exclude 'tiles/*' --exclude 'plugins/*'
#echo -e "${PURPLE} Mondes sauvegardés !${NC}}"

#Sauvergarder la base de données
echo -e "${BLUE} Sauvegarde de la base de données en cours... ${NC}"
mysqldump --all-databases > $backup_path/backup_base-$date.sql -u $USERNAME -p$PASSWORD
echo -e "${PURPLE} Base de données sauvegardée !${NC}"

