#!/bin/bash

#Couleur rouge
RED='\033[0;31m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'

#Pas de couleurs
NC='\033[0m'
 "${PURPLE}arrêt du serveur !${NC}"

#Relancer le serveur
echo -e "${PURPLE} Démarrage du serveur... ${NC}"
cd /home/minecraft/omega && screen -dmS omega java -Xms1G -Xmx1G -XX:+UseG1GC -XX:MaxGCPauseMillis=50 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:TargetSurvivorRatio=90 -XX:G1NewSizePercent=50 -XX:G1MaxNewSizePercent=80 -XX:InitiatingHeapOccupancyPercent=10 -XX:G1MixedGCLiveThresholdPercent=50 -XX:+AggressiveOpts -XX:+AlwaysPreTouch -jar /home/minecraft/omega/paper.jar nogui
