#!/bin/bash

#Declaration des variables
echo -e "Veuillez saisir le nombre à transformer :"
read DECIMAL

echo -e "Veuillez saisir la base de transformation :"
read BASE

declare -r HEX_DIGITS="0123456789ABCDEF"
#declare DECIMAL=$1
declare CHAINE
#declare BASE=$2

#Boucle modulo
while [ $DECIMAL != 0 ]; do

    #Calculer le reste de la division par 16 du nombre saisi
    reste=$((DECIMAL % BASE))

    #Diviser le nombre saisi par 16 pour la prochaine opération
    DECIMAL=$((DECIMAL / BASE))

    #Determiner le caractere hexadecimal par rapport au reste et au caractères enregistrés
    digit=${HEX_DIGITS:$reste:1}

    #Ajouter le caractere hexadecimal à la chaine de caractères hexa
    CHAINE="${digit}${CHAINE}"
#    CHAINE="${reste}${CHAINE}"


#Fin de la boucle quand la variable DECIMAL est 0
done


#Afficher le résultat final
#echo -e ----------------------
#echo -e "Conversion de $1 en base $2 :"
#echo -e
echo -e "Résultat = ${CHAINE}"
#echo -e
#echo -e
#echo -e ----------------------
